version: '3'
services:
    mysqldb:
        image: mysql:8.0.29
        ports:
        - 3307:3306
        environment:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: root
        volumes:
        - ./mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    users-management:
        container_name: users-management
        build:
            context: users-management
            dockerfile: Dockerfile
        image: users-management:latest
        ports:
            - 8084:8084
        depends_on:
             mysqldb:
              condition: service_healthy
        restart: on-failure
    users-management-ui:
        container_name: users-management-ui
        build:
            context: users-management-ui
            dockerfile: Dockerfile
        image: users-management-ui:latest
        ports:
            - 1200:80
        depends_on:
             - users-management
        restart: on-failure
